import {
    HsButton,
    HsButtonGroup,
    HsIcon,
    HsCollapse,
    HsCollapseItem,
    HsAlert,
    HsTooltip,
    HsPopconfirm,
    HsDropdown,
    HsDropdownItem,
    HsMessage,
    HsNotification,
    HsInput,
    HsMessageBox,
    HsLoading,
    HsSwitch,
    HsSelect,
    HsOption,
    HsForm,
    HsFormItem,
} from '@hs-element-ui/components'
import type { Plugin } from 'vue'

export default [
    HsButton,
    HsButtonGroup,
    HsIcon,
    HsCollapse,
    HsCollapseItem,
    HsAlert,
    HsTooltip,
    HsPopconfirm,
    HsDropdown,
    HsDropdownItem,
    HsMessage,
    HsNotification,
    HsInput,
    HsMessageBox,
    HsLoading,
    HsSwitch,
    HsSelect,
    HsOption,
    HsForm,
    HsFormItem,
] as Plugin[]